### ISSUE TITLE
Reason of forking fastonosql

### ISSUE THREAD

**Issue by akalongman** [fastogt/fastoredis#77]
I am curious why you forked [fastonosql](https://github.com/fastogt/fastonosql) and which one we should use

**Comment by topilski** [comment]
We started from FastoRedis which worked only with Redis database and then we understood that there are a lot of NoSQL databases which need our solution. For Redis better use FastoRedis because FastoRedis more lightweight than FastoNoSQL, but if you want access to some other DB please use FastoNoSQL. The differences between FastoRedis and FastoNoSQL only in count of databases.
